bishopmove.o: bishopmove.cpp
	$(CC) $(CPP_VERSION) $(CPPFLAGS) -c bishopmove.cpp -o bishopmove.o

kingmove.o: kingmove.cpp
	$(CC) $(CPP_VERSION) $(CPPFLAGS) -c kingmove.cpp -o kingmove.o

rookmove.o: rookmove.cpp
	$(CC) $(CPP_VERSION) $(CPPFLAGS) -c rookmove.cpp -o rookmove.o

pawnmove.o: pawnmove.cpp
	$(CC) $(CPP_VERSION) $(CPPFLAGS) -c pawnmove.cpp -o pawnmove.o

knightmove.o: knightmove.cpp
	$(CC) $(CPP_VERSION) $(CPPFLAGS) -c knightmove.cpp -o knight.o
